name: Validate Tokenlist

on: [push, pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        env:
          INPUT_SCHEMA: ./src/tokenlist.schema.json
          INPUT_JSONS: ./token.default.json
